### PR TITLE
Add labels for host slave and option to run guest exclusively

### PR DESCRIPTION
**Pull request by atikhono**

### CODE REVIEW

**Comment by atikhono** [comment]
@romankulikov up

**Comment by romankulikov** [comment]
> Add labels to cloud host configuration

And how this is expected to work?

> Add an option to run VMs exclusively

What if I want to run exactly two VMs on the node?

**Comment by atikhono** [comment]
> And how this is expected to work?


A label is configured for the host slave. A job can access that slave by the label.

> What if I want to run exactly two VMs on the node?


Add a textbox for maximum VM count in config.jelly and a validator. Then check `canProvisionAny()` before provisioning.
```
protected boolean canProvisionAny() {
    int vmCount = 0;
    for (final ParallelsDesktopVM vm : vms) {
        if (vm.isProvisioned()) {
            vmCount++;
        }
    }
    return vmCount < maxVMCount;
}
```
Personally I see little practical sense in it. Probably, `provision()` should check that the total resources required by the multiple VMs to be provisioned are not greater that what the host has.

**Comment by romankulikov** [comment]
> A label is configured for the host slave. A job can access that slave by the label.

So this is needed to use host slave as build on node (appropriate checkbox should be enabled)?

**Comment by romankulikov** [comment]
> Personally I see little practical sense in it. Probably, provision() should check that the total resources required by the multiple VMs to be provisioned are not greater that what the host has.

Yes, this is want I want to implement.

**Comment by atikhono** [comment]
> So this is needed to use host slave as build on node (appropriate checkbox should be enabled)?

Exactly. However, this is not a full feature set required for using it as a regular node. Need to implement at least # of executers (it's hard-coded to "1" in the latest plugin). If you look at any node configuration in Jenkins, you'll see it's a bit different. UseAsBuilder is a partially implemented Availability feature. Therefore, useAsBuilder set to false doesn't restrict running jobs on the node. I still can just start the Jenkins client manually and build there (manual launch is controlled by the retention strategy). Also, node properties such as environment variables and tool locations might be useful.

> Yes, this is want I want to implement.

Wow cool, thanks! I've removed my 'runExclusively' patch. The pull request is only labels implementation now.

**Pull request merged**
